/**
 * @fileoverview gRPC-Web generated client stub for greet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: greet.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.greet = require('./greet_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.greet.GreeterClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.greet.GreeterPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.HelloRequest,
 *   !proto.greet.HelloReply>}
 */
const methodDescriptor_Greeter_SayHelloStream = new grpc.web.MethodDescriptor(
  '/greet.Greeter/SayHelloStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.greet.HelloRequest,
  proto.greet.HelloReply,
  /**
   * @param {!proto.greet.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.HelloReply.deserializeBinary
);


/**
 * @param {!proto.greet.HelloRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.greet.HelloReply>}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.sayHelloStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/greet.Greeter/SayHelloStream',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloStream);
};


/**
 * @param {!proto.greet.HelloRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.greet.HelloReply>}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterPromiseClient.prototype.sayHelloStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/greet.Greeter/SayHelloStream',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.HelloRequest,
 *   !proto.greet.HelloReply>}
 */
const methodDescriptor_Greeter_SayHelloTo = new grpc.web.MethodDescriptor(
  '/greet.Greeter/SayHelloTo',
  grpc.web.MethodType.UNARY,
  proto.greet.HelloRequest,
  proto.greet.HelloReply,
  /**
   * @param {!proto.greet.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.HelloReply.deserializeBinary
);


/**
 * @param {!proto.greet.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.greet.HelloReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.greet.HelloReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.sayHelloTo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/greet.Greeter/SayHelloTo',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloTo,
      callback);
};


/**
 * @param {!proto.greet.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.greet.HelloReply>}
 *     Promise that resolves to the response
 */
proto.greet.GreeterPromiseClient.prototype.sayHelloTo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/greet.Greeter/SayHelloTo',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloTo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.HelloRequest,
 *   !proto.greet.HelloReply>}
 */
const methodDescriptor_Greeter_SayHelloToMany = new grpc.web.MethodDescriptor(
  '/greet.Greeter/SayHelloToMany',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.greet.HelloRequest,
  proto.greet.HelloReply,
  /**
   * @param {!proto.greet.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.HelloReply.deserializeBinary
);


/**
 * @param {!proto.greet.HelloRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.greet.HelloReply>}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.sayHelloToMany =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/greet.Greeter/SayHelloToMany',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloToMany);
};


/**
 * @param {!proto.greet.HelloRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.greet.HelloReply>}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterPromiseClient.prototype.sayHelloToMany =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/greet.Greeter/SayHelloToMany',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloToMany);
};


module.exports = proto.greet;

