/**
 * @fileoverview gRPC-Web generated client stub for greet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: greet.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as greet_pb from './greet_pb'; // proto import: "greet.proto"


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHelloStream = new grpcWeb.MethodDescriptor(
    '/greet.Greeter/SayHelloStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    greet_pb.HelloRequest,
    greet_pb.HelloReply,
    (request: greet_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    greet_pb.HelloReply.deserializeBinary
  );

  sayHelloStream(
    request: greet_pb.HelloRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<greet_pb.HelloReply> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/greet.Greeter/SayHelloStream',
      request,
      metadata || {},
      this.methodDescriptorSayHelloStream);
  }

  methodDescriptorSayHelloTo = new grpcWeb.MethodDescriptor(
    '/greet.Greeter/SayHelloTo',
    grpcWeb.MethodType.UNARY,
    greet_pb.HelloRequest,
    greet_pb.HelloReply,
    (request: greet_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    greet_pb.HelloReply.deserializeBinary
  );

  sayHelloTo(
    request: greet_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<greet_pb.HelloReply>;

  sayHelloTo(
    request: greet_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.HelloReply) => void): grpcWeb.ClientReadableStream<greet_pb.HelloReply>;

  sayHelloTo(
    request: greet_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.Greeter/SayHelloTo',
        request,
        metadata || {},
        this.methodDescriptorSayHelloTo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.Greeter/SayHelloTo',
    request,
    metadata || {},
    this.methodDescriptorSayHelloTo);
  }

  methodDescriptorSayHelloToMany = new grpcWeb.MethodDescriptor(
    '/greet.Greeter/SayHelloToMany',
    grpcWeb.MethodType.SERVER_STREAMING,
    greet_pb.HelloRequest,
    greet_pb.HelloReply,
    (request: greet_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    greet_pb.HelloReply.deserializeBinary
  );

  sayHelloToMany(
    request: greet_pb.HelloRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<greet_pb.HelloReply> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/greet.Greeter/SayHelloToMany',
      request,
      metadata || {},
      this.methodDescriptorSayHelloToMany);
  }

}

